added support for -t option
ismnoiet/jekyll-posts-generator pull request #1
Opened 2017-10-29 17:50 UTC by andy5995

* comma separated list of tags now accepted
* any spaces in the comma-separated list will not render correctly

2017-10-29 20:10 UTC, ismnoiet commented
Thank you @andy5995 for your pull request, I will test it tomorrow or the day after and get back to you.

2017-10-29 23:17 UTC, andy5995 commented
Sounds good.

I haven't tested it against your dev branch. I didn't realize that branch existed until after I'd made my changes.

I tested it by copying my revision to /lib/node_modules/jekyll-posts-generator/bin/jposts after I had installed the version available through npm.

I wasn't sure how to test a working copy. I assume it's a matter of editing the path so it will use all the files in my source tree directory.

Anyway, I did the PR against your 'dev' branch.

2017-11-02 01:27 UTC, ismnoiet requested changes
@andy5995 Please add the requested changes and push the commit so I can merge your PR.

2017-11-02 01:27 UTC, ismnoiet commented on bin/jposts
> +  .option('-t, --tags <items>', 'Specify the categor(y/ies) for the current article \n                          example: jposts create <postName> -t tag1,tag2,...')
Please change `Specify the categor(ies)` to `Specify the tag(s)`.

2017-11-02 01:27 UTC, ismnoiet commented on bin/jposts
> +          defaultHeader.tags = options.tags.split(',')
Please, change `options.tags.split(',')` to `options.tags.replace(/[\s]{1,}/g, '').split(',')` so tags with white spaces will be rendered correctly.

2017-11-02 02:03 UTC, andy5995 commented
I rebased, corrected some errors, and I think we have as clean a commit log as we're gonna get! :)

2017-11-02 14:04 UTC, merged